import { useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { apiGet } from '../lib/api-client'
import { authOperation } from '../auth/session-coordinator'
import { useStepUp } from '../auth/use-step-up'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
interface Health {driver:string;stage:string;otpMode:string;googleEnabled:boolean;senderAuthenticated:boolean;budget:{attempts:number;remaining:number;nonOtpRemaining:number};outbox:{pending:number;oldestDueAt:string|null};unknown:number;suppressed:number;lastWebhookAt:string|null;alerts:{id:string;type:string;createdAt:string}[]}
export function AuthHealthPage(){
  const {data,error}=useQuery({queryKey:['auth-health'],queryFn:()=>apiGet<Health>('/auth/admin/health'),refetchInterval:30000}),step=useStepUp(),qc=useQueryClient()
  const [userId,setUserId]=useState(''),[email,setEmail]=useState(''),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  return <div className="space-y-6">{step.view}<h1 className="text-2xl font-semibold">Authentication health</h1>{error&&<p role="alert">Unable to load health. Retry after checking the connection.</p>}{data&&<><div className="grid gap-4 sm:grid-cols-3">{[['Mail driver',data.driver],['Release stage',data.stage],['OTP policy',data.otpMode],['Daily attempts',data.budget.attempts],['Attempts remaining',data.budget.remaining],['Non-OTP remaining',data.budget.nonOtpRemaining],['Queued messages',data.outbox.pending],['Unconfirmed submissions',data.unknown],['Suppressed recipients',data.suppressed]].map(([label,value])=><div key={label} className="border p-4 rounded-lg"><p className="text-sm text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></div>)}</div><p className="text-sm">Google: {data.googleEnabled?'enabled':'disabled'} · Sender authenticated: {data.senderAuthenticated?'configured; external evidence required':'no'} · Last callback: {data.lastWebhookAt?new Date(data.lastWebhookAt).toLocaleString():'none'}</p><h2 className="font-semibold">Operational alerts</h2>{data.alerts.length?data.alerts.map(a=><div className="border-l-4 border-amber-500 p-3 text-sm" key={a.id}>{a.type} · {new Date(a.createdAt).toLocaleString()}</div>):<p className="text-sm text-muted-foreground">No unacknowledged alerts.</p>}</>}
    <form className="max-w-lg space-y-3 border rounded-lg p-5" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const grantToken=await step.request('ADMIN_SUPPRESSION_CLEAR',{userId,email});await authOperation(`/users/${userId}/email-suppression`,{grantToken,reason},{method:'DELETE',protected:true});setMessage('Provider and local suppression cleared. Verify delivery with the recipient.');void qc.invalidateQueries({queryKey:['auth-health']})}catch(e){setMessage(e instanceof Error?e.message:'Could not clear suppression')}finally{setBusy(false)}}}><h2 className="font-semibold">Clear a recipient suppression</h2><p className="text-sm text-muted-foreground">Review the recipient and reason first. For complaints or unsubscribes, record their explicit resubscription request.</p><Label htmlFor="clear-user">Account ID</Label><Input id="clear-user" value={userId} onChange={e=>setUserId(e.target.value)} required/><Label htmlFor="clear-email">Current account email</Label><Input id="clear-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Label htmlFor="clear-reason">Operator reason</Label><Input id="clear-reason" minLength={10} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} required/><Button disabled={busy}>Verify and clear suppression</Button><p role="status" className="text-sm">{message}</p></form>
  </div>
}
